using StoreAndForward;
namespace MoqaLate.Autogenerated
{
public partial class HttpClientMoqaLate : IHttpClient
{


// -------------- Post ------------ 

private PostResult _postReturnValue;

        private int _postNumberOfTimesCalled;

        public IMessage PostParameter_message_LastCalledWith;
        
        public virtual void PostSetReturnValue(PostResult value)
        {
            _postReturnValue = value;
        }    


        public virtual bool PostWasCalled()
{
   return _postNumberOfTimesCalled > 0;
}


public virtual bool PostWasCalled(int times)
{
   return _postNumberOfTimesCalled == times;
}


public virtual int PostTimesCalled()
{
   return _postNumberOfTimesCalled;
}


public virtual bool PostWasCalledWith(IMessage message){
return (
message.Equals(PostParameter_message_LastCalledWith) );
}
 

             public PostResult Post(IMessage message)
        {
            _postNumberOfTimesCalled++;            

            PostParameter_message_LastCalledWith = message;

            return _postReturnValue;
        }}
}
