using StoreAndForward;
namespace MoqaLate.Autogenerated
{
public partial class NewMessageHandlerMoqaLate : INewMessageHandler
{


// -------------- OnMessageAdded ------------


        private int _onMessageAddedNumberOfTimesCalled;        

        public IMessage OnMessageAddedParameter_message_LastCalledWith;

        public virtual bool OnMessageAddedWasCalled()
{
   return _onMessageAddedNumberOfTimesCalled > 0;
}


public virtual bool OnMessageAddedWasCalled(int times)
{
   return _onMessageAddedNumberOfTimesCalled == times;
}


public virtual int OnMessageAddedTimesCalled()
{
   return _onMessageAddedNumberOfTimesCalled;
}


public virtual bool OnMessageAddedWasCalledWith(IMessage message){
return (
message.Equals(OnMessageAddedParameter_message_LastCalledWith) );
}


        public void OnMessageAdded(IMessage message)
        {
            _onMessageAddedNumberOfTimesCalled++;            

            OnMessageAddedParameter_message_LastCalledWith = message;
        }
}
}
