using System.Collections.Generic;
using StoreAndForward;
namespace MoqaLate.Autogenerated
{
public partial class StoreMoqaLate : IStore
{
// ------------ Property Count
private int _Count;
public virtual int Count
{
get { return _Count; }
}
public virtual void __SetCount(int val)
{
   _Count = val;
}


// -------------- Add ------------ 

private IMessage _addReturnValue;

        private int _addNumberOfTimesCalled;

        public IMessage AddParameter_message_LastCalledWith;
        
        public virtual void AddSetReturnValue(IMessage value)
        {
            _addReturnValue = value;
        }    


        public virtual bool AddWasCalled()
{
   return _addNumberOfTimesCalled > 0;
}


public virtual bool AddWasCalled(int times)
{
   return _addNumberOfTimesCalled == times;
}


public virtual int AddTimesCalled()
{
   return _addNumberOfTimesCalled;
}


public virtual bool AddWasCalledWith(IMessage message){
return (
message.Equals(AddParameter_message_LastCalledWith) );
}
 

             public IMessage Add(IMessage message)
        {
            _addNumberOfTimesCalled++;            

            AddParameter_message_LastCalledWith = message;

            return _addReturnValue;
        }

// -------------- Remove ------------


        private int _removeNumberOfTimesCalled;        

        public IMessage RemoveParameter_message_LastCalledWith;

        public virtual bool RemoveWasCalled()
{
   return _removeNumberOfTimesCalled > 0;
}


public virtual bool RemoveWasCalled(int times)
{
   return _removeNumberOfTimesCalled == times;
}


public virtual int RemoveTimesCalled()
{
   return _removeNumberOfTimesCalled;
}


public virtual bool RemoveWasCalledWith(IMessage message){
return (
message.Equals(RemoveParameter_message_LastCalledWith) );
}


        public void Remove(IMessage message)
        {
            _removeNumberOfTimesCalled++;            

            RemoveParameter_message_LastCalledWith = message;
        }


// -------------- Get ------------ 

private IList<IMessage> _getReturnValue;

        private int _getNumberOfTimesCalled;

        
        
        public virtual void GetSetReturnValue(IList<IMessage> value)
        {
            _getReturnValue = value;
        }    


        public virtual bool GetWasCalled()
{
   return _getNumberOfTimesCalled > 0;
}


public virtual bool GetWasCalled(int times)
{
   return _getNumberOfTimesCalled == times;
}


public virtual int GetTimesCalled()
{
   return _getNumberOfTimesCalled;
}


 

             public IList<IMessage> Get()
        {
            _getNumberOfTimesCalled++;            

            

            return _getReturnValue;
        }}
}
